spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kis:
  appkey: "PSD64gaxdXbILn8ad7LYQrKHujTVxlydAKiq"
  appsecret: "yHvyGFQiCbdmY8CXLe62/48/pID3JKOC7/4ElbdqnARCcDbmRwzB5idQ4HOTLGTEBUQIQN8X3L8xmoxa1jXZn80GXgl9DWZVfqKhxbYYfT6Nbnhvxdc4z9YW9/x6RCMWFEvZGwrFU/zoCJjA/21S/VCgbJ/P7mRPlbIADfFZx6b6kkTNvCE="
  grant-type: client_credentials
  token-url: https://openapi.koreainvestment.com:9443/oauth2/tokenP

springdoc:
  api-docs:
    path: /v3/api-docs       # Swagger JSON 문서 경로
  swagger-ui:
    path: /swagger-ui.html   # Swagger UI 브라우저 접속 경로
    operationsSorter: method
    tagsSorter: alpha
